#ifndef SYMBOLS_H
#define SYMBOLS_H

enum SYMBOL_VALUES {
		    INCREASE_CURRENT_CELL,
		    DECREASE_CURRENT_CELL,
		    ZERO_CURRENT_CELL,

		    MOVE_NEXT_CELL,
		    MOVE_PREVIOUS_CELL,
		    MOVE_ZERO_CELL,

		    PUT_CELL_TO_STACK,
		    GET_CELL_FROM_STACK,

		    ADD_STACK,
		    SUB_STACK,
		    MUL_STACK,
		    DIV_STACK,

		    CYCLE_BEGIN,
		    CYCLE_END,

		    CHECK_EQUAL,
		    CHECK_LESS,
		    CHECK_GREATER,

		    JMP,
		    JMP_IF,
};

#endif
