# - Try to find OpenAL-soft (custom)
# Once done, this will define
#
# OPENALSOFT_FOUND - system has OpenAL-soft
# OPENALSOFT_INCLUDE_DIR - the OpenAL-soft include directories
# OPENALSOFT_LIBRARIES - link these to use OpenAL-soft
FIND_PATH( OPENALSOFT_INCLUDE_DIR AL/al.h
	/usr/include
	/usr/local/include
	/opt/local/include
	"${CMAKE_SOURCE_DIR}/include"
)
FIND_LIBRARY( OPENALSOFT_LIBRARY OpenAL32
	/usr/lib64
	/usr/lib
	/usr/local/lib
	/opt/local/lib
	"${CMAKE_SOURCE_DIR}/lib"
)
IF(OPENALSOFT_INCLUDE_DIR AND OPENALSOFT_LIBRARY)
	SET( OPENALSOFT_FOUND TRUE )
ENDIF(OPENALSOFT_INCLUDE_DIR AND OPENALSOFT_LIBRARY)
IF(OPENALSOFT_FOUND)
	IF(NOT OPENALSOFT_FIND_QUIETLY)
	MESSAGE(STATUS "Found OpenAL-soft: ${OPENALSOFT_LIBRARY}")
	ENDIF(NOT OPENALSOFT_FIND_QUIETLY)
ELSE(OPENALSOFT_FOUND)
	IF(OPENALSOFT_FIND_REQUIRED)
	MESSAGE(FATAL_ERROR "Could not find OpenAL32")
	ENDIF(OPENALSOFT_FIND_REQUIRED)
ENDIF(OPENALSOFT_FOUND)
